import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

const Section = ({ title, content, colorClass, defaultOpen = true }) => {
  const [isOpen, setIsOpen] = useState(defaultOpen);

  return (
    <motion.div 
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className={`border-l-4 ${colorClass} bg-[var(--color-bg-card)] rounded-r-xl p-4 mb-4 border border-y-[var(--color-border)] border-r-[var(--color-border)] overflow-hidden`}
    >
      <div 
        className="flex justify-between items-center cursor-pointer mb-2"
        onClick={() => setIsOpen(!isOpen)}
      >
        <h3 className="font-semibold text-lg text-white">{title}</h3>
        <motion.div animate={{ rotate: isOpen ? 180 : 0 }}>
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-gray-400">
            <path d="m6 9 6 6 6-6"/>
          </svg>
        </motion.div>
      </div>
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.2 }}
          >
            <p className="text-gray-300 leading-relaxed text-sm mt-2">{content}</p>
            {title === 'Plan' && (
              <div className="mt-4 p-3 bg-amber-500/10 border border-amber-500/20 rounded-md flex items-start gap-2">
                <span className="text-amber-500 mt-0.5">⚠️</span>
                <p className="text-amber-500 text-xs font-medium">Doctor must review before prescribing.</p>
              </div>
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

const SOAPNote = ({ data }) => {
  if (!data) return null;

  const container = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.15 }
    }
  };

  return (
    <motion.div 
      variants={container}
      initial="hidden"
      animate="show"
      className="w-full relative pb-6"
    >
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-bold text-white">Clinical Note (SOAP)</h2>
      </div>
      
      <Section title="Subjective" content={data.s} colorClass="border-l-blue-500" />
      <Section title="Objective" content={data.o} colorClass="border-l-purple-500" />
      <Section title="Assessment" content={data.a} colorClass="border-l-amber-500" />
      <Section title="Plan" content={data.p} colorClass="border-l-emerald-500" />
      
      <div className="absolute bottom-0 right-2 text-[10px] text-gray-500 font-medium">
        Generated by Gemini
      </div>
    </motion.div>
  );
};

export default SOAPNote;
