import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

const Section = ({ title, content, defaultOpen = true }) => {
  const [isOpen, setIsOpen] = useState(defaultOpen);

  return (
    <motion.div 
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className="border-l-4 border-l-[#0D9488] bg-[#F8F9FA] rounded-r-xl p-4 mb-4 border border-[#E5E7EB] overflow-hidden"
    >
      <div 
        className="flex justify-between items-center cursor-pointer mb-2"
        onClick={() => setIsOpen(!isOpen)}
      >
        <h3 className="font-medium text-base text-[#111827]">{title}</h3>
        <motion.div animate={{ rotate: isOpen ? 180 : 0 }}>
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-[#9CA3AF]">
            <path d="m6 9 6 6 6-6"/>
          </svg>
        </motion.div>
      </div>
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.2 }}
          >
            <p className="text-[#374151] leading-relaxed text-sm mt-2">{content}</p>
            {title === 'Plan' && (
              <div className="mt-4 p-3 bg-[#FEF3C7] border border-[#D97706]/20 rounded-md flex items-start gap-2">
                <span className="text-[#D97706] mt-0.5">⚠️</span>
                <p className="text-[#D97706] text-xs font-medium">Doctor must review before prescribing.</p>
              </div>
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

const SOAPNote = ({ data }) => {
  if (!data) return null;

  const container = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.15 }
    }
  };

  return (
    <motion.div 
      variants={container}
      initial="hidden"
      animate="show"
      className="w-full relative pb-6"
    >
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-xl font-medium text-[#111827]">Clinical Note (SOAP)</h2>
      </div>
      
      <Section title="Subjective" content={data.s} />
      <Section title="Objective" content={data.o} />
      <Section title="Assessment" content={data.a} />
      <Section title="Plan" content={data.p} />
      
      <div className="absolute bottom-0 right-2 text-[10px] text-[#9CA3AF] font-medium">
        Generated by Gemini
      </div>
    </motion.div>
  );
};

export default SOAPNote;
